choices = [
    ("ゲームのタイトル", "pygame.display.set_caption('Simple shooting')"),
    ("敵のx座標", "100"),
    ("弾の見た目の形", "pygame.Surface((5, 10))"),
    ("ゲームの窓を作る", "pygame.display.set_mode((WIDTH, HEIGHT))"),
    ("敵に当たったか調べる", "pygame.sprite.groupcollide(bullets, enemies, True, True)"),
    ("弾を撃つ間隔", "60"),
    ("敵グループ", "pygame.sprite.Group()"),
    ("敵の弾を作る", "Bullet(enemy.rect.centerx, enemy.rect.bottom, 7, BLUE)"),
    ("プレイヤーの弾を作る", "Bullet(player.rect.centerx, player.rect.top, -10, YELLOW)"),
    ("敵の見た目の形", "pygame.Surface((40, 30))"),
    ("敵の初期移動方向", "1"),
    ("プレイヤーのスピード", "6"),
    ("敵の色", "RED"),
    ("プレイヤーの弾グループ", "pygame.sprite.Group()"),
    ("敵の弾グループ", "pygame.sprite.Group()"),
    ("FPS", "60"),
    ("弾の色", "color"),
    ("プレイヤーに当たったか調べる", "pygame.sprite.spritecollideany(player, enemy_bullets)"),
    ("プレイヤーの見た目の形", "pygame.Surface((50,20))"),
    ("敵の間隔", "80"),
    ("敵の数", "8"),
    ("30%の確率で弾を撃つ", "random.random() < 0.3"),
    ("プレイヤーのグループを作る", "pygame.sprite.Group(player)"),
    ("敵が下に下がる量", "20"),
    ("ゲームのメッセージ条件式", '"SUGEE" if not enemies else "OSHIMAI"'),
    ("弾が画面外に出たかどうかの条件", "self.rect.bottom < 0 or self.rect.top > HEIGHT"),
    ("背景色", "(0, 0, 0)"),
    ("ゲームを始める", "pygame.init()"),
    ("敵の横スピード", "2"),
    ("敵のy座標", "100"),
]
